import Head from 'next/head';
import { TITLE, recommends, FORM_STEP } from '../../utils/constants';
import {
  SolarIrradianceByMonth,
  SolarIrradianceByWeek,
  OptimalSolarRecommendation,
  PotentialSolarGenerationInYourRegion,
} from '../../components/bar-chart';
import {
  Card,
  CardHeader,
  CardContent,
  IconButton,
  Box,
  Paper,
  Container,
  Typography,
  TableContainer,
  Table,
  TableBody,
  TableRow,
  TableCell,
  TableHead,
  Tabs,
  Tab,
} from '@mui/material';
import InfoIcon from '@mui/icons-material/Info';
import { SecondaryHeader } from '../../components/header';
import React, { useEffect } from 'react';
import { TabPanel } from '../../components/tab-panel';
import { AlertDialog } from '../../components/dialog';
import { fetchData } from '../../api/fetch-data';

interface Props {
  address: string;
  provider: string;
  averageBill: string;
}

interface EventProps {
  setStep: (step) => void;
}

const Report = (props: Props & EventProps) => {
  const [data, setData] = React.useState(null);
  const [tabIndex, setTabIndex] = React.useState(0);
  const [openDialog, setOpenDialog] = React.useState(false);
  const { address, provider, averageBill } = props;
  const handleBack = () => {
    const { setStep } = props;
    setStep(FORM_STEP.FIRST);
  };

  useEffect(() => {
    window.scrollTo(0, 0);
    async function getData() {
      const data = await fetchData();
      setData(data);
    }
    getData();
  }, []);

  console.log(data);

  const handleChangeTab = (event: React.SyntheticEvent, newValue: number) => {
    setTabIndex(newValue);
  };

  const handleOpenDialog = () => {
    setOpenDialog(true);
  };

  return (
    <div>
      <Head>
        <title>{TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SecondaryHeader onClick={handleBack} />
      <Container maxWidth="md" component="main" sx={{ my: 4 }}>
        <Paper elevation={0}>
          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0' }}>
            <Card>
              <CardHeader
                title={
                  <Typography component="p" sx={{ textTransform: 'uppercase' }}>
                    What we know about you
                  </Typography>
                }
              />
              <CardContent sx={{ textAlign: 'center' }}>
                <TableContainer>
                  <Table>
                    <TableBody>
                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Location
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            {address}
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Solar provider
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            {provider}
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Average monthly electric bill
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            ${averageBill || 0}
                          </Typography>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </TableContainer>
              </CardContent>
            </Card>
          </Box>

          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0', mt: 2 }}>
            <Card>
              <CardHeader
                title={
                  <Typography component="p" sx={{ textTransform: 'uppercase' }}>
                    Setup to cover your needs
                  </Typography>
                }
              />
              <CardContent sx={{ textAlign: 'center' }}>
                <TableContainer>
                  <Table>
                    <TableBody>
                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Solar panel area
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            100m<sup>2</sup>
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Number of solar panels
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            5
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Cost
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            $1000
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Maintenance
                          </Typography>
                          <Typography variant="subtitle1" component="span">
                            Once every year
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            $1000
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Saving per month
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            $100
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Break-even
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            10 months
                          </Typography>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </TableContainer>
              </CardContent>
            </Card>
          </Box>

          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0', mt: 2 }}>
            <Card>
              <CardHeader
                title={
                  <Typography component="p" sx={{ textTransform: 'uppercase' }}>
                    Sunshine in your area
                  </Typography>
                }
              />
              <Tabs value={tabIndex} onChange={handleChangeTab}>
                <Tab label="By Month" />
                <Tab label="By Week" />
              </Tabs>

              <TabPanel value={tabIndex} index={0}>
                <Card>
                  <CardContent>
                    <SolarIrradianceByMonth />
                  </CardContent>
                </Card>
              </TabPanel>

              <TabPanel value={tabIndex} index={1}>
                <Card>
                  <CardContent>
                    <SolarIrradianceByWeek />
                  </CardContent>
                </Card>
              </TabPanel>
            </Card>
          </Box>

          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0', mt: 2 }}>
            <Card>
              <CardHeader
                title={
                  <Typography component="p" sx={{ textTransform: 'uppercase' }}>
                    Optimal Solar Recommendation
                  </Typography>
                }
              />
              <CardContent>
                <OptimalSolarRecommendation />
              </CardContent>
            </Card>
          </Box>

          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0', mt: 2 }}>
            <Card>
              <CardHeader
                action={
                  <IconButton onClick={handleOpenDialog}>
                    <InfoIcon />
                  </IconButton>
                }
                title={
                  <Typography component="p" sx={{ textTransform: 'uppercase' }}>
                    Recommended angle setup
                  </Typography>
                }
              />
              <CardContent sx={{ textAlign: 'center' }}>
                <TableContainer>
                  <Table>
                    <TableHead>
                      <TableRow>
                        <TableCell>Month</TableCell>
                        <TableCell align="right">Angle</TableCell>
                        <TableCell align="right">Orientation</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {recommends.map((item, index) => {
                        return (
                          <TableRow key={index}>
                            <TableCell>
                              <Typography variant="body1" component="p">
                                {item.month}
                              </Typography>
                            </TableCell>
                            <TableCell align="right">
                              <Typography variant="body1" component="p">
                                {item.angle}
                              </Typography>
                            </TableCell>
                            <TableCell align="right">
                              <Typography variant="body1" component="p">
                                {item.orientation}
                              </Typography>
                            </TableCell>
                          </TableRow>
                        );
                      })}
                    </TableBody>
                  </Table>
                </TableContainer>
              </CardContent>
            </Card>
          </Box>


          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0', mt: 2 }}>
            <Card>
              <CardHeader
                title={
                  <Typography component="p" sx={{ textTransform: 'uppercase' }}>
                    Potential Solar Generation In The Region
                  </Typography>
                }
              />
              <CardContent>
                <PotentialSolarGenerationInYourRegion />
              </CardContent>
            </Card>
          </Box>
        </Paper>
      </Container>
      <AlertDialog open={openDialog} setOpen={setOpenDialog} />
    </div>
  );
};

export { Report };
