import Head from 'next/head';
import { TITLE, recommends } from '../utils/constants';
import { BarChart } from '../components/bar-chart'
import {
  Card,
  CardHeader,
  CardContent,
  IconButton,
  Box,
  Paper,
  Container,
  Typography,
  TableContainer,
  Table,
  TableBody,
  TableRow,
  TableCell,
  TableHead,
} from '@mui/material';
import InfoIcon from '@mui/icons-material/Info';
import type { NextPage } from 'next';

const Report: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="sm" component="main" sx={{ my: 10 }}>
        <Paper elevation={0}>
          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0' }}>
            <Card>
              <CardHeader
                action={
                  <IconButton>
                    <InfoIcon />
                  </IconButton>
                }
                title={
                  <Typography component="p">
                    YOUR INFORMATION
                  </Typography>
                }
              />
              <CardContent sx={{ textAlign: 'center' }}>
                <TableContainer>
                  <Table>
                    <TableBody>
                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Location
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            Singapore
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Solar provider
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            Sembcorp
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Average monthly electric bill
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            $300
                          </Typography>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </TableContainer>
              </CardContent>
            </Card>
          </Box>

          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0', mt: 2 }}>
            <Card>
              <CardHeader
                action={
                  <IconButton>
                    <InfoIcon />
                  </IconButton>
                }
                title={
                  <Typography component="p">
                    SUNSHINE LAST YEAR
                  </Typography>
                }
              />
              <CardContent sx={{ textAlign: 'center' }}>
                <BarChart />
              </CardContent>
            </Card>
          </Box>

          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0', mt: 2 }}>
            <Card>
              <CardHeader
                action={
                  <IconButton>
                    <InfoIcon />
                  </IconButton>
                }
                title={
                  <Typography component="p">
                    SOLAR PANEL INSTALLATION
                  </Typography>
                }
              />
              <CardContent sx={{ textAlign: 'center' }}>
                <TableContainer>
                  <Table>
                    <TableBody>
                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Cost
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            1000 SGD
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Maintenance
                          </Typography>
                          <Typography variant="subtitle1" component="span">
                            Once every 5 years
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            1000 SGD
                          </Typography>
                        </TableCell>
                      </TableRow>

                      <TableRow>
                        <TableCell>
                          <Typography variant="h6" component="h6">
                            Break-even
                          </Typography>
                        </TableCell>
                        <TableCell align="right">
                          <Typography variant="body1" component="p">
                            10 months
                          </Typography>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </TableContainer>
              </CardContent>
            </Card>
          </Box>

          <Box sx={{ border: 1, borderRadius: 1, borderColor: '#dadce0', mt: 2 }}>
            <Card>
              <CardHeader
                action={
                  <IconButton>
                    <InfoIcon />
                  </IconButton>
                }
                title={
                  <Typography component="p">
                    RECOMMEND SETUP
                  </Typography>
                }
              />
              <CardContent sx={{ textAlign: 'center' }}>
                <TableContainer>
                  <Table>
                    <TableHead>
                      <TableRow>
                        <TableCell>Month</TableCell>
                        <TableCell align="right">Angle</TableCell>
                        <TableCell align="right">Equator-facing orientation</TableCell>
                        <TableCell align="right">Saving per month</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {recommends.map((item, index) => {
                        return (
                          <TableRow key={index}>
                            <TableCell>
                              <Typography variant="body1" component="p">
                                {item.month}
                              </Typography>
                            </TableCell>
                            <TableCell align="right">
                              <Typography variant="body1" component="p">
                                {item.angle}
                              </Typography>
                            </TableCell>
                            <TableCell align="right">
                              <Typography variant="body1" component="p">
                                {item.orientation}
                              </Typography>
                            </TableCell>
                            <TableCell align="right">
                              <Typography variant="body1" component="p">
                                {item.saving}
                              </Typography>
                            </TableCell>
                          </TableRow>
                        )
                      })}

                    </TableBody>
                  </Table>
                </TableContainer>
              </CardContent>
            </Card>
          </Box>
        </Paper>
      </Container>
    </div>
  );
};

export default Report;
